#!/bin/bash

pkglist_deepin=(
    compiz
    dbus-generator
    dde-account-faces
    dde-api
    dde-control-center
    dde-daemon
    dde-dock-applets
    dde-go-dbus-factory
    dde-qml-dbus-factory
    dde-qml-gettext-plugin
    dde-workspace
    deepin-artwork
    deepin-artwork-themes
    deepin-boot-maker
    deepin-bug-reporter
    deepin-cursor-theme
    deepin-default-gsettings
    deepin-default-settings
    deepin-default-settings-tuning
    deepin-desktop-environment
    deepin-desktop-environment-common
    deepin-desktop-environment-dock
    deepin-desktop-environment-dosd
    deepin-desktop-environment-launcher
    deepin-desktop-environment-lock
    deepin-download-service
    deepin-emacs
    deepin-emacs-common
    deepin-firefox-addons
    deepin-game-center
    deepin-gettext-tools
    deepin-gtk-theme
    deepin-icon-theme
    deepin-icon-theme-v2013
    deepin-installer
    deepin-menu
    deepin-movie
    deepin-music-player
    deepin-mutter
    deepin-mutter-common
    deepin-notifications
    deepin-os-upgrader
    deepin-qml-widgets
    deepin-screenshot
    deepin-software-center
    deepin-software-center-data
    deepin-terminal
    deepin-ui
    deepin-wm
    dmusic-plugin-baidumusic
    golang-dlib-dev
    grub-themes-deepin
    libdeepin-mutter0d
    libdeepin-mutter-dev
    libdeepin-webkit-3.0-0
    libvte9
    libvte-common
    python-deepin-gsettings
    python-deepin-storm
    python-deepin-utils
    python-vte
    startdde
)

pkglist_archlinux=(
    dde-account-faces
    dde-api
    dde-control-center
    dde-daemon
    dde-dock-applets
    dde-go-dbus-factory
    dde-qml-dbus-factory
    dde-workspace
    deepin-artwork
    deepin-artwork-themes
    deepin-compiz
    deepin-cursor-theme
    deepin-dbus-generator
    deepin-default-gsettings
    deepin-gettext-tools
    deepin-gtk-theme
    deepin-icon-theme
    deepin-icon-theme-v2013
    deepin-menu
    deepin-movie
    deepin-music-player
    deepin-notifications
    deepin-pygtk
    deepin-qml-widgets
    deepin-screenshot
    deepin-terminal
    deepin-ui
    deepin-vte
    go-dlib
    grub-theme-deepin
    libdeepin-webkit
    lightdm-deepin-greeter
    python2-deepin-gsettings
    python2-deepin-storm
    python2-deepin-utils
    python2-deepin-xrandr
    startdde
)
