post_install() {
  glib-compile-schemas --allow-any-name usr/share/glib-2.0/schemas

  useradd -r -s /usr/bin/nologin deepin-daemon
  
  if [ -f /usr/share/applications/polkit-gnome-authentication-agent-1.desktop ]; then
      cp -f /usr/share/applications/polkit-gnome-authentication-agent-1.desktop /etc/xdg/autostart/
      sed -i 's/\(OnlyShowIn=.*\)/\1Deepin;/' /etc/xdg/autostart/polkit-gnome-authentication-agent-1.desktop 
  fi

  if [ -f /usr/share/applications/nm-applet.desktop ]; then
      cp -f /usr/share/applications/nm-applet.desktop /etc/xdg/autostart/
      sed -i 's/\(NotShowIn=.*\)/\1Deepin;/' /etc/xdg/autostart/nm-applet.desktop
  fi
}

post_upgrade() {
  glib-compile-schemas --allow-any-name usr/share/glib-2.0/schemas
}

post_remove() {
  rm -f /var/log/deepin.log
  rm -f /var/cache/deepin/mark-setup-network-services
  userdel -r deepin-daemon
}
