--- dde-api-0.0.2/makefile.old	2014-05-09 05:06:05.000000000 +0200
+++ dde-api-0.0.2/makefile	2014-05-19 22:56:50.054103929 +0200
@@ -1,14 +1,14 @@
-run:=go build -o .out && rm .out
+run:=go build && cd ..
 
 all: 
 	cd graphic/ && $(run)
 	cd grub2ext/ && $(run)
 	cd logger/ && $(run)
+	cd lunar-calendar/ && $(run)
 	cd mousearea/ && $(run)
 	cd pinyin-search/ && $(run)
 	cd set-date-time/ && $(run)
 	cd sound/ && $(run)
-	cd utils/ && $(run)
 
 
 update:
